# -*- coding: utf-8 -*-
"""Ecommerce_sales_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3MEVOSf0t83B0PjHV3Or76Kjh1C3Ege
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv('final_ecommerce_dataset.csv')
df.head()

#  Convert date columns to datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'], errors='coerce')
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'], errors='coerce')
df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'], errors='coerce')

# Create Order Month column
df['Order_Month'] = df['order_purchase_timestamp'].dt.to_period('M').astype(str)

#  Create Total Sales column
df['Total_Sales'] = df['price'] + df['payment_value']

# Calculate Delivery Time
df['Delivery_Days'] = (
    df['order_delivered_customer_date'] - df['order_purchase_timestamp']
).dt.days

#  Clean missing values
df['product_category_name'].fillna("Unknown", inplace=True)
df['customer_city'].fillna("Unknown", inplace=True)
df['payment_type'].fillna("Unknown", inplace=True)

# 7️⃣ Create useful metrics
df['Order_Year'] = df['order_purchase_timestamp'].dt.year
df['Order_Month_Name'] = df['order_purchase_timestamp'].dt.month_name()

# Aggregate dataset for dashboards
dashboard_df = df.groupby([
    'Order_Month',
    'customer_city',
    'product_category_name',
    'payment_type'
]).agg(
    Total_Revenue=('Total_Sales', 'sum'),
    Total_Orders=('order_id', 'nunique'),
    Total_Items=('order_item_id', 'count'),
    Avg_Delivery_Time=('Delivery_Days', 'mean')
).reset_index()

# Save final dataset
dashboard_df.to_csv("ecommerce_dashboard_ready.csv", index=False)

print("Dataset prepared successfully for Tableau dashboards!")

from google.colab import files
files.download('ecommerce_dashboard_ready.csv')

















